#!/bin/bash
version=0.1.7

GREEN="\033[1;32m"
RED="\033[1;31m"
CYAN="\033[1;36m"
NC="\033[0m"
echo -e "${GREEN}Coolinette${NC} v${version}"

# Check if first (project) argument is supplied
if [ -z "$1" ]; then
	echo -e "Auto-detecting project..."
	dn="${PWD##*/}"
	case "$dn" in
		*"Shell00"* | *"shell00"* | *"Shell 00"* | *"shell 00"*)
			proj="Shell00"	
			;;
		*"Shell01"* | *"shell01"* | *"Shell 01"* | *"shell 01"*)
			proj="Shell01"	
			;;
		*"C00"* | *"c00"* | *"C 00"* | *"c 00"*)
			proj="C00"	
			;;
		*"C01"* | *"c01"* | *"C 01"* | *"c 01"*)
			proj="C01"	
			;;
		*"C02"* | *"c02"* | *"C 02"* | *"c 02"*)
			proj="C02"	
			;;
		*"C03"* | *"c03"* | *"C 03"* | *"c 03"*)
			proj="C03"	
			;;
		*"C04"* | *"c04"* | *"C 04"* | *"c 04"*)
			proj="C04"	
			;;
		*"C05"* | *"c05"* | *"C 05"* | *"c 05"*)
			proj="C05"	
			;;
		*"C06"* | *"c06"* | *"C 06"* | *"c 06"*)
			proj="C06"	
			;;
		*"C07"* | *"c07"* | *"C 07"* | *"c 07"*)
			proj="C07"	
			;;
		*)
			echo -e "${RED}Cannot detect project:${NC} Exiting..."
			exit 1
			;;	
	esac
else
	if [ "$1" == "update" ]; then
		echo -e "${CYAN}Updating Coolinette${NC}..."
		cd ${HOME}/coolinette/
		git pull
		exit 1
	fi
	proj=$1
fi

echo -e "Selected project ${CYAN}${proj}${NC}"
# Check if second (exercise) argument is supplied
if [ -z "$2" ]; then

	bash "${HOME}/coolinette/scripts/${proj}.sh"
else
	bash "${HOME}/coolinette/scripts/${proj}.sh" "${2}"
fi
